
version: 2

sources:
  - name: gog_raw_data
    description: "Surowe dane transakcyjne z platformy GOG."
    tables:
      - name: raw_transactions
        description: "Surowe dane o transakcjach (sprzedaż gier, subskrypcje itp.)."
        columns:
          - name: transaction_id
            description: "Unikalny identyfikator transakcji."
            tests:
              - unique
              - not_null
          - name: user_id
            description: "Identyfikator użytkownika dokonującego transakcji."
          - name: game_id
            description: "Identyfikator zakupionej gry."
          - name: transaction_date
            description: "Data i czas transakcji."
          - name: amount
            description: "Kwota transakcji w oryginalnej walucie."
          - name: currency
            description: "Waluta transakcji."
          - name: payment_method
            description: "Użyta metoda płatności (np. karta, PayPal)."
          - name: product_type
            description: "Typ produktu (np. gra, subskrypcja)."

      - name: exchange_rates
        description: "Dzienne kursy wymiany walut."
        columns:
          - name: date
            description: "Data, dla której obowiązuje kurs."
          - name: currency_from
            description: "Waluta źródłowa."
          - name: currency_to
            description: "Waluta docelowa."
          - name: rate
            description: "Kurs wymiany."

      - name: game_metadata
        description: "Metadane dotyczące gier."
        columns:
          - name: game_id
            description: "Unikalny identyfikator gry."
            tests:
              - unique
              - not_null
          - name: game_title
            description: "Tytuł gry."
          - name: genre
            description: "Gatunek gry."
          - name: developer
            description: "Deweloper gry."
          - name: release_date
            description: "Data wydania gry."

      - name: psp_transactions
        description: "Dane transakcyjne od dostawcy usług płatniczych (PSP)."
        columns:
          - name: psp_transaction_id
            description: "Unikalny identyfikator transakcji od PSP."
            tests:
              - unique
              - not_null
          - name: original_transaction_id
            description: "Klucz łączący z tabelą raw_transactions.transaction_id."
          - name: psp_amount
            description: "Kwota transakcji zarejestrowana przez PSP."
          - name: psp_currency
            description: "Waluta zarejestrowana przez PSP."
          - name: psp_timestamp
            description: "Sygnatura czasowa transakcji od PSP."
          - name: status
            description: "Status transakcji od PSP (np. success, failed)."
